#!/usr/bin/node
// print a message depending of the number of argument passed

import { argv } from 'node:process';

if (argv.length == 0){
	console.log("No argument");
} else if (argv.length == 1){
	console.log("Argument found");
} else {
	console.log("Arguments found");
}

